import Head from "next/head";
import styles from "../../styles/Layout.module.css";
import NavigationBar from "./NavigationBar";
import Footer from "./Footer";

export default function Home(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Mnemeric</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.headerContainer}>
                <NavigationBar />
            </header>

            <div className={styles.bodyContainer}>
                <div className={styles.bodyContentContainer}>
                    {props.children}
                </div>
            </div>

            <footer className={styles.footerContainer}>
                <Footer />
            </footer>
        </div>
    );
}
